// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210427173506_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BussinessModels.DBModels.SaleMain", b =>
                {
                    b.Property<int>("AgentID")
                        .HasColumnType("int");

                    b.Property<int>("AgentID2")
                        .HasColumnType("int");

                    b.Property<string>("BillNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("BiltyExp")
                        .HasColumnType("real");

                    b.Property<int>("BiltyNo")
                        .HasColumnType("int");

                    b.Property<int>("BrachID")
                        .HasColumnType("int");

                    b.Property<string>("CashAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CashRece")
                        .HasColumnType("real");

                    b.Property<float>("ChangeReturn")
                        .HasColumnType("real");

                    b.Property<string>("ChqRece")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CommissionExp")
                        .HasColumnType("real");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditDays")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<float>("DiscountUser")
                        .HasColumnType("real");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("FreightExp")
                        .HasColumnType("real");

                    b.Property<float>("GSale")
                        .HasColumnType("real");

                    b.Property<string>("Goods")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("N1")
                        .HasColumnType("int");

                    b.Property<int>("N2")
                        .HasColumnType("int");

                    b.Property<int>("N3")
                        .HasColumnType("int");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<float>("OtherExp")
                        .HasColumnType("real");

                    b.Property<float>("PKTQty")
                        .HasColumnType("real");

                    b.Property<float>("Packet")
                        .HasColumnType("real");

                    b.Property<string>("Pandi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Post")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SAccID")
                        .HasColumnType("int");

                    b.Property<int>("SMID")
                        .HasColumnType("int");

                    b.Property<float>("SReturn")
                        .HasColumnType("real");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("txt1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("txt2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("txt3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SaleMains");
                });

            modelBuilder.Entity("BussinessModels.DBModels.SaleSub", b =>
                {
                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<float>("Bardana")
                        .HasColumnType("real");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<float>("CommisionPer")
                        .HasColumnType("real");

                    b.Property<float>("CommisionRs")
                        .HasColumnType("real");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<float>("DisPer")
                        .HasColumnType("real");

                    b.Property<float>("DisRS")
                        .HasColumnType("real");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<float>("NetRate")
                        .HasColumnType("real");

                    b.Property<float>("Packet")
                        .HasColumnType("real");

                    b.Property<float>("PktQty")
                        .HasColumnType("real");

                    b.Property<float>("Qty")
                        .HasColumnType("real");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<int>("SMID")
                        .HasColumnType("int");

                    b.Property<string>("STRG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<float>("Tulai")
                        .HasColumnType("real");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SaleSubs");
                });

            modelBuilder.Entity("BussinessModels.DBModels.SaleSubWarehouse", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<int>("GodownID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<float>("Packet")
                        .HasColumnType("real");

                    b.Property<float>("PktQty")
                        .HasColumnType("real");

                    b.Property<float>("Qty")
                        .HasColumnType("real");

                    b.Property<int>("SMID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.ToTable("SaleSubWarehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
