// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210614110833_changeCityTable")]
    partial class changeCityTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BussinessModels.DBModels.Adda", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleU")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Adda");
                });

            modelBuilder.Entity("BussinessModels.DBModels.Agents", b =>
                {
                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<string>("IdCardNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("[ID] IS NOT NULL");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("BussinessModels.DBModels.BuisnessNature", b =>
                {
                    b.Property<string>("BNCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BNID")
                        .HasColumnType("int");

                    b.Property<string>("BNTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("BuisnessNature");
                });

            modelBuilder.Entity("BussinessModels.DBModels.City", b =>
                {
                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityNameU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("[ID] IS NOT NULL");

                    b.ToTable("City");
                });

            modelBuilder.Entity("BussinessModels.DBModels.CodeCodingCategory", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CateID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CodeCodingCategory");
                });

            modelBuilder.Entity("BussinessModels.DBModels.CodeCodingMain", b =>
                {
                    b.Property<float?>("AdminMinRate")
                        .HasColumnType("real");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("BoraQty")
                        .HasColumnType("real");

                    b.Property<float?>("BoxQty")
                        .HasColumnType("real");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<float?>("BundleQty")
                        .HasColumnType("real");

                    b.Property<float>("CID")
                        .HasColumnType("real");

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("CommRate")
                        .HasColumnType("real");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<float?>("CostRate")
                        .HasColumnType("real");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("MinRate")
                        .HasColumnType("real");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<int?>("OptionsID")
                        .HasColumnType("int");

                    b.Property<int>("PCateID")
                        .HasColumnType("int");

                    b.Property<int>("PTypeID")
                        .HasColumnType("int");

                    b.Property<float?>("SaleRate")
                        .HasColumnType("real");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("[ID] IS NOT NULL");

                    b.ToTable("CodeCodingMain");
                });

            modelBuilder.Entity("BussinessModels.DBModels.CodeCodingOptions", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<int>("OptionID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CodeCodingOptions");
                });

            modelBuilder.Entity("BussinessModels.DBModels.CodeCodingProductType", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.ToTable("CodeCodingProductType");
                });

            modelBuilder.Entity("BussinessModels.DBModels.CodeCodingProduction", b =>
                {
                    b.Property<float?>("Astar")
                        .HasColumnType("real");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<float>("CID")
                        .HasColumnType("real");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<float?>("Gatta")
                        .HasColumnType("real");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<float?>("InnerMaterial")
                        .HasColumnType("real");

                    b.Property<float?>("Pages")
                        .HasColumnType("real");

                    b.Property<float?>("Printing")
                        .HasColumnType("real");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<float?>("TitleMaterial")
                        .HasColumnType("real");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("[ID] IS NOT NULL");

                    b.ToTable("CodeCodingProduction");
                });

            modelBuilder.Entity("BussinessModels.DBModels.CodeCodingWarehouse", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<float>("CID")
                        .HasColumnType("real");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<int?>("GodownID")
                        .HasColumnType("int");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<float?>("Qty")
                        .HasColumnType("real");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("[ID] IS NOT NULL");

                    b.ToTable("CodeCodingWarehouse");
                });

            modelBuilder.Entity("BussinessModels.DBModels.Customers", b =>
                {
                    b.Property<int>("AgentID1")
                        .HasColumnType("int");

                    b.Property<int?>("AgentID2")
                        .HasColumnType("int");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<string>("CName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CreditLimit")
                        .HasColumnType("real");

                    b.Property<string>("CustType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MainGroupID")
                        .HasColumnType("int");

                    b.Property<float>("OpBal")
                        .HasColumnType("real");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SAccID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("WhatsappNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("[ID] IS NOT NULL");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BussinessModels.DBModels.GenMain", b =>
                {
                    b.Property<float>("BCID")
                        .HasColumnType("real");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinID")
                        .HasColumnType("int");

                    b.Property<int>("HeadID")
                        .HasColumnType("int");

                    b.Property<string>("Narat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpertorID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.ToTable("GenMain");
                });

            modelBuilder.Entity("BussinessModels.DBModels.GenSub", b =>
                {
                    b.Property<string>("AccDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccID")
                        .HasColumnType("int");

                    b.Property<float>("BCID")
                        .HasColumnType("real");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<float>("CrAmt")
                        .HasColumnType("real");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<float>("DrAmt")
                        .HasColumnType("real");

                    b.Property<int>("FinID")
                        .HasColumnType("int");

                    b.Property<string>("Narat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpertorID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.ToTable("GenSub");
                });

            modelBuilder.Entity("BussinessModels.DBModels.GoDown", b =>
                {
                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoCid")
                        .HasColumnType("int");

                    b.Property<string>("GoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoNameU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("[ID] IS NOT NULL");

                    b.ToTable("GoDown");
                });

            modelBuilder.Entity("BussinessModels.DBModels.Ledger", b =>
                {
                    b.Property<int>("Acc_code")
                        .HasColumnType("int");

                    b.Property<float>("Cr")
                        .HasColumnType("real");

                    b.Property<float>("DisPer")
                        .HasColumnType("real");

                    b.Property<float>("DisRs")
                        .HasColumnType("real");

                    b.Property<float>("Dr")
                        .HasColumnType("real");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("LGID")
                        .HasColumnType("real");

                    b.Property<DateTime>("LG_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("LG_Narat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LG_NaratU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LG_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("OperatorID")
                        .HasColumnType("smallint");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<string>("SAccName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAccNameU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SID")
                        .HasColumnType("real");

                    b.Property<int>("branchid")
                        .HasColumnType("int");

                    b.Property<string>("chqno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("packetqty")
                        .HasColumnType("real");

                    b.ToTable("Ledger");
                });

            modelBuilder.Entity("BussinessModels.DBModels.Lot", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<string>("LotType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleU")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Lot");
                });

            modelBuilder.Entity("BussinessModels.DBModels.Pandi", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<string>("PandiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PerPhaira")
                        .HasColumnType("real");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("[ID] IS NOT NULL");

                    b.ToTable("Pandi");
                });

            modelBuilder.Entity("BussinessModels.DBModels.SaleMain", b =>
                {
                    b.Property<int?>("AgentID")
                        .HasColumnType("int");

                    b.Property<int?>("AgentID2")
                        .HasColumnType("int");

                    b.Property<string>("BillNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("BiltyExp")
                        .HasColumnType("real");

                    b.Property<int?>("BiltyNo")
                        .HasColumnType("int");

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("CashAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("CashRece")
                        .HasColumnType("real");

                    b.Property<float?>("ChangeReturn")
                        .HasColumnType("real");

                    b.Property<string>("ChqRece")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("CommissionExp")
                        .HasColumnType("real");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreditDays")
                        .HasColumnType("int");

                    b.Property<int?>("Del")
                        .HasColumnType("int");

                    b.Property<float?>("DiscountUser")
                        .HasColumnType("real");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("FreightExp")
                        .HasColumnType("real");

                    b.Property<float?>("GSale")
                        .HasColumnType("real");

                    b.Property<string>("Goods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<int?>("N1")
                        .HasColumnType("int");

                    b.Property<int?>("N2")
                        .HasColumnType("int");

                    b.Property<int?>("N3")
                        .HasColumnType("int");

                    b.Property<int?>("OperatorID")
                        .HasColumnType("int");

                    b.Property<float?>("OtherExp")
                        .HasColumnType("real");

                    b.Property<float?>("PKTQty")
                        .HasColumnType("real");

                    b.Property<float?>("Packet")
                        .HasColumnType("real");

                    b.Property<string>("Pandi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Post")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SAccID")
                        .HasColumnType("int");

                    b.Property<int?>("SMID")
                        .HasColumnType("int");

                    b.Property<float?>("SReturn")
                        .HasColumnType("real");

                    b.Property<int?>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("txt1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("txt2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("txt3")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("[ID] IS NOT NULL");

                    b.ToTable("SaleMain");
                });

            modelBuilder.Entity("BussinessModels.DBModels.SaleParty", b =>
                {
                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BCID")
                        .HasColumnType("int");

                    b.Property<string>("BalType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<float>("CID")
                        .HasColumnType("real");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ControlACCID")
                        .HasColumnType("real");

                    b.Property<float>("CreditLimit")
                        .HasColumnType("real");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("N1")
                        .HasColumnType("smallint");

                    b.Property<short>("N2")
                        .HasColumnType("smallint");

                    b.Property<short>("N3")
                        .HasColumnType("smallint");

                    b.Property<short>("N4")
                        .HasColumnType("smallint");

                    b.Property<string>("NTN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("OPBal")
                        .HasColumnType("real");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<string>("PartyConcate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartyType")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaleMan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("[ID] IS NOT NULL");

                    b.ToTable("SaleParty");
                });

            modelBuilder.Entity("BussinessModels.DBModels.SaleReturnMain", b =>
                {
                    b.Property<int>("AccID")
                        .HasColumnType("int");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<float>("DiscountUser")
                        .HasColumnType("real");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SMID")
                        .HasColumnType("int");

                    b.Property<int>("SRID")
                        .HasColumnType("int");

                    b.Property<float>("SReturn")
                        .HasColumnType("real");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.ToTable("SaleReturnMain");
                });

            modelBuilder.Entity("BussinessModels.DBModels.SaleReturnSub", b =>
                {
                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int?>("Del")
                        .HasColumnType("int");

                    b.Property<float>("DisPer")
                        .HasColumnType("real");

                    b.Property<int>("GodownID")
                        .HasColumnType("int");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int>("ItemD")
                        .HasColumnType("int");

                    b.Property<float>("NetTotal")
                        .HasColumnType("real");

                    b.Property<float>("Qty")
                        .HasColumnType("real");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<int>("SMID")
                        .HasColumnType("int");

                    b.Property<int>("SRID")
                        .HasColumnType("int");

                    b.Property<int?>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("itemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SaleReturnSub");
                });

            modelBuilder.Entity("BussinessModels.DBModels.SaleSub", b =>
                {
                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<float?>("Bardana")
                        .HasColumnType("real");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<float?>("CommisionPer")
                        .HasColumnType("real");

                    b.Property<float?>("CommisionRs")
                        .HasColumnType("real");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<float>("DisPer")
                        .HasColumnType("real");

                    b.Property<float>("DisRS")
                        .HasColumnType("real");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<float>("NetRate")
                        .HasColumnType("real");

                    b.Property<float?>("Packet")
                        .HasColumnType("real");

                    b.Property<float?>("PktQty")
                        .HasColumnType("real");

                    b.Property<float>("Qty")
                        .HasColumnType("real");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<int>("SMID")
                        .HasColumnType("int");

                    b.Property<int>("SSID")
                        .HasColumnType("int");

                    b.Property<string>("STRG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<float?>("Tulai")
                        .HasColumnType("real");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("[ID] IS NOT NULL");

                    b.ToTable("SaleSub");
                });

            modelBuilder.Entity("BussinessModels.DBModels.SaleSubWarehouse", b =>
                {
                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int?>("Del")
                        .HasColumnType("int");

                    b.Property<int?>("GodownID")
                        .HasColumnType("int");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int?>("ItemID")
                        .HasColumnType("int");

                    b.Property<float?>("Packet")
                        .HasColumnType("real");

                    b.Property<float?>("PktQty")
                        .HasColumnType("real");

                    b.Property<float?>("Qty")
                        .HasColumnType("real");

                    b.Property<int>("SMID")
                        .HasColumnType("int");

                    b.Property<int>("SSID")
                        .HasColumnType("int");

                    b.Property<int>("SWID")
                        .HasColumnType("int");

                    b.Property<int?>("Sync")
                        .HasColumnType("int");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("[ID] IS NOT NULL");

                    b.ToTable("SaleSubWarehouse");
                });

            modelBuilder.Entity("BussinessModels.DBModels.SalesOutSourceItems", b =>
                {
                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("SMID")
                        .HasColumnType("int");

                    b.Property<int>("SOID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("[ID] IS NOT NULL");

                    b.ToTable("SalesOutSourceItems");
                });

            modelBuilder.Entity("BussinessModels.DBModels.Schools", b =>
                {
                    b.Property<int>("AgentID1")
                        .HasColumnType("int");

                    b.Property<int?>("AgentID2")
                        .HasColumnType("int");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CreditLimit")
                        .HasColumnType("real");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MainGroupID")
                        .HasColumnType("int");

                    b.Property<float>("OpBal")
                        .HasColumnType("real");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Principal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SAccID")
                        .HasColumnType("int");

                    b.Property<string>("SchlType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolBranches")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolStrength")
                        .HasColumnType("int");

                    b.Property<string>("SessionStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("WhatsappNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("BussinessModels.DBModels.adAccountTransactionTypes", b =>
                {
                    b.Property<int>("AccTransTypeID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("compID")
                        .HasColumnType("int");

                    b.ToTable("adAccountTransactionTypes");
                });

            modelBuilder.Entity("BussinessModels.DBModels.adAccountTypes", b =>
                {
                    b.Property<int>("AccTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("compID")
                        .HasColumnType("int");

                    b.ToTable("adAccountTypes");
                });

            modelBuilder.Entity("BussinessModels.DBModels.adAccounts", b =>
                {
                    b.Property<string>("AccFlexCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccID")
                        .HasColumnType("int");

                    b.Property<int>("AccTransTypeID")
                        .HasColumnType("int");

                    b.Property<int>("AccTypeID")
                        .HasColumnType("int");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CateAccID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CtrlAccID")
                        .HasColumnType("int");

                    b.Property<int>("CtrlAccIDCr")
                        .HasColumnType("int");

                    b.Property<int>("CtrlAccIDDr")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupAccID")
                        .HasColumnType("int");

                    b.Property<int>("MainGroupID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("accCodeCr")
                        .HasColumnType("int");

                    b.Property<int>("accCodeDr")
                        .HasColumnType("int");

                    b.Property<float>("accCreditLimit")
                        .HasColumnType("real");

                    b.Property<float>("accOpenBal")
                        .HasColumnType("real");

                    b.Property<string>("accURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("areaID")
                        .HasColumnType("int");

                    b.Property<int>("cityID")
                        .HasColumnType("int");

                    b.Property<int>("compID")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isAutoOpenBal")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeptAcc")
                        .HasColumnType("bit");

                    b.Property<bool>("isFreeze")
                        .HasColumnType("bit");

                    b.Property<bool>("isLocationAcc")
                        .HasColumnType("bit");

                    b.Property<bool>("isNtnActive")
                        .HasColumnType("bit");

                    b.Property<string>("ntNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("opBalType")
                        .HasColumnType("int");

                    b.Property<string>("stNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("adAccounts");
                });

            modelBuilder.Entity("BussinessModels.DBModels.adCategoryAccounts", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CateAccID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinStatementTypeID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("accHeadID")
                        .HasColumnType("int");

                    b.Property<string>("accHeadName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("compID")
                        .HasColumnType("int");

                    b.ToTable("adCategoryAccounts");
                });

            modelBuilder.Entity("BussinessModels.DBModels.adControlAccounts", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CateAccID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompID")
                        .HasColumnType("int");

                    b.Property<int>("CtrlAccID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("accCodeId")
                        .HasColumnType("int");

                    b.Property<string>("accCodeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("adControlAccounts");
                });

            modelBuilder.Entity("BussinessModels.DBModels.adFinancialStatementCategories", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinStatementCateID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("compID")
                        .HasColumnType("int");

                    b.ToTable("adFinancialStatementCategories");
                });

            modelBuilder.Entity("BussinessModels.DBModels.adFinancialStatementTypes", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinStatementCateID")
                        .HasColumnType("int");

                    b.Property<int>("FinStatementTypeID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("compID")
                        .HasColumnType("int");

                    b.ToTable("adFinancialStatementTypes");
                });

            modelBuilder.Entity("BussinessModels.DBModels.adGroupAccounts", b =>
                {
                    b.Property<int>("AccTypeID")
                        .HasColumnType("int");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CateAccID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompID")
                        .HasColumnType("int");

                    b.Property<int>("CtrlAccID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupAccID")
                        .HasColumnType("int");

                    b.Property<int>("MainGroupID")
                        .HasColumnType("int");

                    b.Property<int>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isChild")
                        .HasColumnType("bit");

                    b.Property<bool>("isCoaItem")
                        .HasColumnType("bit");

                    b.ToTable("adGroupAccounts");
                });

            modelBuilder.Entity("BussinessModels.DBModels.adMainGroupAccounts", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CateAccID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CtrlAccID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MainGroupID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("compID")
                        .HasColumnType("int");

                    b.ToTable("adMainGroupAccounts");
                });

            modelBuilder.Entity("BussinessModels.DBModels.cdCompanies", b =>
                {
                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.Property<int>("businessNatureID")
                        .HasColumnType("int");

                    b.Property<string>("companyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.Property<byte[]>("companyLogo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("companyNTN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companySTN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyTitleU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("corporateLogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("corporatePWD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isActive")
                        .HasColumnType("bit");

                    b.ToTable("cdCompanies");
                });

            modelBuilder.Entity("BussinessModels.DBModels.mClassMain", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int>("CStatus")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.ToTable("mClassMain");
                });

            modelBuilder.Entity("BussinessModels.DBModels.mClassSub", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int>("ClassTypeID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.ToTable("mClassSub");
                });

            modelBuilder.Entity("BussinessModels.DBModels.mClassType", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("Del")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int>("OperatorID")
                        .HasColumnType("int");

                    b.Property<int>("Sync")
                        .HasColumnType("int");

                    b.ToTable("mClassType");
                });
#pragma warning restore 612, 618
        }
    }
}
